version: '3.1'
services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379

  postgres-server:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
