
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/uaa
    username: postgres
    password:
    pool:
      enabled: true
  data:
    r2dbc:
      repositories:
        enabled: true
server:
  port: 8080