server:
  port: 8080
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/uaa
    username: postgres
    password: 123456
    initialization-mode: always
    separator: ;;

---
spring:
  profiles: docker
  redis:
    host: redis-server
    port: 6379
    password: 123456
    database: 0
  r2dbc:
    url: r2dbc:postgresql://postgres-server:5432/uaa
    username: postgres
    password: 123456
    initialization-mode: always
    separator: ;;